#! /bin/sh

bspc config border_width        2
bspc config window_gap          5 
bspc config top_padding        14

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focused_border_color "#cc99cc"

bspc monitor DP-0 -n L -d I II III IV V
bspc monitor DVI-I-1 -n R -d VI VII VIII IX X

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Minecraft floating=on
bspc rule -a Spotify floating=on
bspc rule -a VirtualBox floating=on
bspc rule -a Pidgin floating=on
bspc rule -a Skype floating=on
bspc rule -a Dia floating=on

panel &
