#! /bin/sh

bspc config border_width        1
bspc config window_gap          4
bspc config top_padding        13

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config auto_cancel         true
bspc config focused_border_color "#cc99cc"

bspc monitor DP-0 -n L -d I II III IV V
# bspc monitor DVI-I-1 -d $(echo -e '\uf109') $(echo -e '\uf121') $(echo -e '\uf120') $(echo -e '\uf07c') $(echo -e '\uf0ac') $(echo -e '\uf0c3') $(echo -e '\uf141') $(echo -e '\uf001')
bspc monitor DVI-I-1 -n R -d VI VII VIII IX X

bspc rule -a Gimp desktop=^8 follow=on state=floating
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 state=floating
bspc rule -a Minecraft state=floating
bspc rule -a Spotify state=floating
bspc rule -a VirtualBox state=floating
bspc rule -a Pidgin state=floating
bspc rule -a Skype state=floating
bspc rule -a Dia state=floating
bspc rule -a Telegram state=floating
bspc rule -a nylas state=floating
bspc rule -a zeal state=floating
bspc rule -a crx_nckgahadagoaajjgafhacjanaoiihapd state=floating follow=on
bspc rule -a Speedbar state=floating follow=on
bspc rule -a electron state=floating follow=on
bspc rule -a emacs-capture state=floating follow=on

panel &
